# Generated by Django 2.2.2 on 2019-07-03 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_auto_20190703_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherdetail',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
