# Generated by Django 2.2.2 on 2019-06-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('short_form', models.CharField(help_text='For example BCT for BE Computer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject_code', models.CharField(max_length=20)),
                ('year', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=5)),
                ('part', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=5)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFullAndPassMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_practical', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], max_length=30)),
                ('pass_marks', models.IntegerField()),
                ('full_marks', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.Batch')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='MarksInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3)),
                ('part', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=3)),
                ('theory_practical', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], max_length=30)),
                ('group', models.CharField(max_length=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.Batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MarksDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('marks_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.MarksInstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.Student')),
            ],
        ),
    ]
