# Generated by Django 2.2.2 on 2019-06-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0002_auto_20190611_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='short_form',
            field=models.CharField(help_text='For example BCT for BE Computer', max_length=10, unique=True),
        ),
    ]
