# Generated by Django 2.2.2 on 2019-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0003_auto_20190611_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksinstance',
            name='part',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II')], max_length=3),
        ),
        migrations.AlterField(
            model_name='marksinstance',
            name='year',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='part',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II')], max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=1),
        ),
    ]
