# Generated by Django 2.2.2 on 2019-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0004_auto_20190724_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksinstance',
            name='batch',
            field=models.CharField(choices=[('2070', '2070'), ('2071', '2071'), ('2072', '2072'), ('2073', '2073'), ('2074', '2074'), ('2075', '2075')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(choices=[('2070', '2070'), ('2071', '2071'), ('2072', '2072'), ('2073', '2073'), ('2074', '2074'), ('2075', '2075')], max_length=4),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
