# Generated by Django 2.2.2 on 2019-07-24 17:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0005_auto_20190724_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksinstance',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='marksinstance',
            name='name_of_examiner',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='marksinstance',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.Programme'),
        ),
        migrations.AlterField(
            model_name='marksdetail',
            name='marks_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im.MarksInstance'),
        ),
    ]
