# Generated by Django 2.2.2 on 2019-07-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0006_auto_20190724_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksinstance',
            name='full_mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marksinstance',
            name='pass_mark',
            field=models.IntegerField(null=True),
        ),
    ]
