# Generated by Django 2.2.2 on 2019-07-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0007_auto_20190724_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('programme', 'batch', 'roll_number')},
        ),
    ]
