# Generated by Django 2.2.2 on 2019-08-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0008_auto_20190724_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=1)),
                ('part', models.CharField(choices=[('1', 'I'), ('2', 'II')], max_length=1)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('theory_full_marks', models.IntegerField(default=0, help_text='Full marks of theory')),
                ('practical_full_marks', models.IntegerField(default=0, help_text='Full marks of theory')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.Programme')),
            ],
        ),
        migrations.AlterModelOptions(
            name='marksinstance',
            options={'ordering': ('-id',), 'permissions': (('can_enter_result', 'Can take test'),)},
        ),
        migrations.AlterField(
            model_name='marksinstance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='im.SubjectDetail'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im.SubjectDetail'),
        ),
    ]
