# Generated by Django 2.2.2 on 2019-08-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0009_auto_20190803_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksdetail',
            name='marks',
            field=models.CharField(max_length=4),
        ),
    ]
