# Generated by Django 2.2.2 on 2019-08-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0010_auto_20190803_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='im.Department'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='part',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=1),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=1),
        ),
        migrations.AlterField(
            model_name='marksinstance',
            name='part',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=3),
        ),
        migrations.AlterField(
            model_name='marksinstance',
            name='theory_practical',
            field=models.CharField(choices=[('Th', 'Theory'), ('Pr', 'Practical')], max_length=30),
        ),
        migrations.AlterField(
            model_name='marksinstance',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3),
        ),
    ]
