# Generated by Django 2.2.2 on 2019-08-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0011_auto_20190803_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='part',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=4),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_detail', to='im.Programme'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=4),
        ),
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to='im.Department'),
        ),
    ]
