# Generated by Django 2.2.2 on 2019-07-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_form', models.CharField(help_text='This is the abbreviated form that is used in roll number. For example BCT for Computer Engineering', max_length=5)),
            ],
        ),
    ]
