# Generated by Django 2.2.2 on 2019-07-03 15:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0002_auto_20190703_1502'),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')])),
                ('from_time', models.TimeField(default=datetime.datetime.now)),
                ('to_time', models.TimeField(default=datetime.datetime.now)),
                ('subject', models.CharField(blank=True, help_text='Can be anything like break presentation etc, not necesserily a subject from syllabus', max_length=100, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authuser.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')])),
                ('part', models.IntegerField(choices=[(1, 'I'), (2, 'II')])),
                ('group', models.CharField(max_length=1)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='information.Programme')),
            ],
        ),
    ]
